project:
  type: website

website:
  title: "Heart Disease Prediction by Age and Gender"
  navbar:
    left:
      - href: Index.qmd
        text: Home
      - href: index2.qmd
        text: Visuals
      - href: MODEL1.qmd
        text: MODEL
      - href: About.qmd
        text: About
      - href: Source.qmd
        text: Source

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




